### ISSUE TITLE
Walking child_modules of child_modules

### ISSUE THREAD

**Issue by willrubel-mxr** [fugue/regula#100]
We have module calling modules, thus, we have 3-4 levels deep of resources.  Currently, when calling the fugue.resource function, we are not obtaining all resources.

**Comment by curtis-fugue** [comment]
Hi @willrubel-mxr. Regula currently operates on Terraform plan files, which may be created behind-the-scenes, depending on how you are using it. Will you check if the resources you are expecting to see are in fact present in the Terraform plan files that you're operating on?

You can see how Regula generates the plan here:
https://github.com/fugue/regula/blob/master/bin/regula#L116-L120

Running `terraform show -json your-plan-file` can be used to inspect the plan.

**Comment by ameliafugue** [comment]
Hi @willrubel-mxr,
 
Did you have a chance to try the solution @curtis-fugue suggested? 

We’ll close this ticket in 7 days if we don’t hear back.
