### ISSUE TITLE
generate-test-inputs.sh - unable to test local modules

### ISSUE THREAD

**Issue by dwilliams782** [fugue/regula#111]
Hi all,

Following from my last post in #109, I've been setting up unit tests via conftest, and have hit a bit of an issue.

The rule shared in #109 checks for the module source and compares it to a whitelist, and supports nested modules as well. Some of our TF environments utilise local modules made up of remote modules.

In `generate-test-inputs.sh`:

```
function generate_test_input {
  if [[ $# -ne 2 ]]; then
    1>&2 echo "Usage: $0 INFRA_FILE REGO_FILE"
    exit 1
  fi

  local workdir="$(mktemp -d)"
  trap "rm -rf "$workdir"" return
  cp "$1" "$workdir"
```

this creates a temp directory and copies the rule's TF input file over to init (smart!) however this then breaks the relative path to the local modules I've added alongside the `x_test.rego` file:

```
module "child_module_source_valid" {
  source  = "./test_module/"
  project = local.project
}
```
I haven't really got a smart solution for this ATM, I think I'm probably just going to hardcode in the bash script to copy a directory of local test modules over to the temporary directory on each run, but I thought it was worthwhile mentioning anyway.

**Comment by dwilliams782** [comment]
``` 
function generate_test_input {
  if [[ $# -ne 2 ]]; then
    1>&2 echo "Usage: $0 INFRA_FILE REGO_FILE"
    exit 1
  fi

  local workdir="$(mktemp -d)"
  trap "rm -rf "$workdir"" return
  cp "$1" "$workdir"

  # Switch based on extension.  The inner branches must generate
  # `$workdir/infra.json` which will be spliced into the rego file.
  local extension="${1##*.}"
  if [[ "$extension" == "tf" ]]; then
    cp -R tests/rules/tf/google/inputs/local_test_modules "$workdir"
```

I've added a directory for all my local test modules and just copy them in to every new temp dir. It's not ideal but it's functional for now.

**Comment by ameliafugue** [comment]
Hi @dwilliams782, 

Thanks for bringing this to our attention. It makes sense for us to support this use-case
and we're in the process of discussing how to make this fit with the upcoming changes to
Regula. We'll leave this ticket open while we work on a solution.
