### ISSUE TITLE
support for CIS AWS version 1.4.0

### ISSUE THREAD

**Issue by chrisdlangton** [fugue/regula#124]
Last time #59 the issue was closed without a clue if/when CIS AWS version 1.3.0 would be completed  (or even started).

This time, let's get an idea when 1.4.0 will be started **and keep the issue open** until the issue subject matter is completed or you decide to abandon the latest CIS AWS benchmark version

**Comment by ameliafugue** [comment]
Hi @chrisdlangton, 

Adding support for CIS AWS 1.4.0 Benchmark is currently a roadmap item.

**Comment by ameliafugue** [comment]
Closing this as the v1.5.0 release supports CIS AWS v1.4.0 and CIS Google v1.2.0. [Link to the latest deploy:](https://github.com/fugue/regula/releases/tag/v1.5.0)
