### ISSUE TITLE
Regula reports incorrect 'filepath'

### ISSUE THREAD

**Issue by christophetd** [fugue/regula#128]
When running Regula against a directory:

```
regula run . --include ../rules --include waivers.rego --user-only
```

It reports a `filepath` that is not valid (`.` instead of being `test.tf`):

```
+----------------------+---------------+----------+----------+--------------+--------------------------+---------+--------+
|       Resource       |     Type      | Filepath | Severity |   Rule ID    |        Rule Name         | Message | Result |
+----------------------+---------------+----------+----------+--------------+--------------------------+---------+--------+
| aws_s3_bucket.bucket | aws_s3_bucket | .        | Unknown  | S3_ENCRYPTED | aws_s3_bucket_encryption |         | WAIVED |
+----------------------+---------------+----------+----------+--------------+--------------------------+---------+--------+
|                      |               |          |          |              |                          | Overall |   PASS |
+----------------------+---------------+----------+----------+--------------+--------------------------+---------+--------+
```

Same thing if using the JSON output format.

I believe the exact file name in which the resource is defined should be shown.

- Should be relatively easy when scanning Terraform code
- Might arguably be more complex when scanning a Terraform plan. See checkov implementation: https://github.com/bridgecrewio/checkov/pull/1221 and sample usage https://twitter.com/christophetd/status/1397981313924280326

**Comment by ameliafugue** [comment]
Hi @christophetd, 

I created a bug ticket for tracking purposes. The work is slated to be completed in Q2.

**Comment by ameliafugue** [comment]
Hi @christophetd 

This issue was resolved with the [Regula v.1.0.0 deploy](https://github.com/fugue/regula/releases/tag/v1.0.0).
