### ISSUE TITLE
regula show input for folder

### ISSUE THREAD

**Issue by marioerceg** [fugue/regula#149]
Hi,

When I try to pass folder with TF code to "regula show input" command I am getting errors like “FATAL Unable to detect input type of file terraform.tfvars” or README.md etc.

Thanks,
Mario

**Comment by jason-fugue** [comment]
Hi, @marioerceg! Could you please clarify how you're passing the folder to `regula show input`?

**Comment by marioerceg** [comment]
Hi Jason. Sorry, it seems I used ./* instead of the folder. If I pass only main file main.tf where I have only resources from modules then it returns zero resources. Should it be like that? Thanks!

**Comment by jason-fugue** [comment]
Ah yeah, `regula show input ./*` could definitely pick up some non-terraform files. If you want regula to pick up everything in your folder, I'd recommend running it like this:

```
regula show input .
```

When you pass a directory to regula, it'll recurse through that directory to find files that it recognizes. You've already figured out the issue with `./*`, but just a brief explanation for anyone else who comes across this ticket - your shell expands out the `./*` before invoking regula, so it's equivalent to running `regula show input main.tf terraform.tfvars README.md`. Regula ignores files that it doesn't recognize when its recursing through a directory, but it will report errors for any individual files that you give it.

**Comment by jason-fugue** [comment]
> If I pass only main file main.tf where I have only resources from modules then it returns zero resources. Should it be like that?

Sorry I forgot to address this question - yes, that's expected. Running it like this: `regula show input main.tf`, regula will only load the contents of `main.tf`. It sounds like you would need to run it on the directory to get the behavior you want.

One other potential gotcha regarding modules is that regula will only evaluate local files at this time. If you want regula to evaluate resources that come from remote modules (like from the module registry, github, etc.), you'll want to run `terraform init` first to download the modules before running regula.

**Comment by marioerceg** [comment]
Thanks Jason! All clear. 

Will it be possible soon to run "regula show input" against TF json plan file? 
If I understood well it does some formatting before passing it to regula, doesn't it?

**Comment by jason-fugue** [comment]
No problem! I'm glad to hear it.

> Will it be possible soon to run "regula show input" against TF json plan file?

This works with the current version of regula:

```
# From inside of a terraform config directory
terraform init
terraform plan -refresh=false -out="plan.tfplan"
terraform show -json "plan.tfplan" > ./plan.json
regula show input plan.json
```

> If I understood well it does some formatting before passing it to regula, doesn't it?

Our goal is for rules to produce the same results for both Terraform HCL code (`.tf` files) and Terraform plan JSON files. But, yes you will see differences between Terraform HCL and Terraform plan files with `regula show input`.

`regula show input` prints out a kind of "raw" representation that gets passed into our rego code. We use that command to help us debug issues with that initial transformation. There's another transformation that happens before anything gets passed to the rules. We could probably do more to document exactly what transformations we're doing, but [this page in our documentation](https://regula.dev/development/test-inputs.html#viewing-test-inputs) describes how to look at them.

Just a brief overview of what those are:

* `mock_config` - this is the `content` field that you see with `regula show input`.
* `mock_input` - this is what `input` is set to for "advanced rules".
* `mock_resources` - this is just the `resources` field from `mock_input`. For "simple rules" we set `input` to one resource at a time depending on the `resource_type` specified in the rule.

Regarding differences between HCL code and Terraform plan files: if you are getting different rule results for HCL code and Terraform plan files, that's something that we'd like to understand and potentially fix. So, feel free to open issues for those - they'd be much appreciated!

**Comment by ameliafugue** [comment]
Closing this issue as we have not heard a response back.
