### ISSUE TITLE
Feature suggestion: Pick specific checks from the Regula library

### ISSUE THREAD

**Issue by christophetd** [fugue/regula#165]
checkov has this feature (through `--check` / `--skip-check`) to include or exclude specific rules. It would be very helpful in Regula as well

Examples:

```
$ regula run . --include-rules FG_R00278,FG_R00279
$ regula run . --exclude-rules FG_R00278
```

I realize that rules can be currently excluded using [waivers](https://regula.dev/configuration.html#disabling-rules), but I would say it makes sense to do it with the CLI as well (easier in some cases) 

Another (more tricky use-case) is when you have a mix of custom rules that you all want to apply, and Regula built-in rules you want to pick from; what would be your approach here?

**Comment by jason-fugue** [comment]
Hi, @christophetd! We recently added two new flags to `regula run` that hopefully fit this use-case:

```
  -x, --exclude strings         Rule IDs or names to exclude. Can be specified multiple times.
  -o, --only strings            Rule IDs or names to run. All other rules will be excluded. Can be specified multiple times.
```

The help text mentions that they can be specified multiple times, but it also works with the syntax that you suggested:

```
regula run --only FG_R00278,FG_R00279
regula run --exclude FG_R00278
```

Whenever you get a chance, could you please take a look and see if those new flags fulfill this feature suggestion?

**Comment by christophetd** [comment]
Looks great 👏🏼 Thank you!
