### ISSUE TITLE
Is regula.dev site working for someone?

### ISSUE THREAD

**Issue by amioranza** [fugue/regula#173]
I'm trying to access the regula.dev site but it is broken:
![image](https://user-images.githubusercontent.com/30518346/129610898-259414e3-23a6-47d4-987e-3a66a5d5e3f9.png)

Is it only for me or someone else has the same problem?

**Comment by jason-fugue** [comment]
Hi, @amioranza! I'm having trouble reproducing that issue. It looks like at least some of the site is loading, but not all of it. Whenever you get a chance, could you please help us narrow down the issue?

Some troubleshooting steps that would be helpful for us:
* Is it working in other browsers that you have installed?
* Are there any errors showing up in the Javascript console?
  * To get to the Javascript console: right click on the page, click "Inspect", then click on "Console" in the panel that opens up
* Are there errors in the network tab for some assets?
  * To get to the network tab, use the same instructions as above, but click on "Network"

Thanks!

**Comment by amioranza** [comment]
Hi, sure!

All 3 browser I have has the same problem when loading regule.dev:
![image](https://user-images.githubusercontent.com/30518346/129614645-fd00fba0-82a9-4f02-ad71-ab384557582a.png)

This is the JS errors:
![image](https://user-images.githubusercontent.com/30518346/129614711-420a0339-c03a-49c8-a145-2780b8c13488.png)

No errors on network tab:
![image](https://user-images.githubusercontent.com/30518346/129614809-72a7bb90-af41-437a-b8ad-3aff432803c8.png)

**Comment by amioranza** [comment]
Firefox on my cellphone has the same problem.

**Comment by jason-fugue** [comment]
Thanks! Would you mind clicking on `bundle.a1609d9a.min.js` in the network tab and see what it has in the preview? That error in the console and the size of that response make me think that it's not actually loading those JS files.

**Comment by amioranza** [comment]
Sure, np:
![image](https://user-images.githubusercontent.com/30518346/129615901-fc9ba47b-2c57-4f52-9b92-64fc33afa958.png)

**Comment by amioranza** [comment]
Curl returned exact the same content:
![image](https://user-images.githubusercontent.com/30518346/129616287-5418b2e1-0407-446d-bcd2-d5ecee9e1405.png)

The header points to some cloudfront cache error

**Comment by amioranza** [comment]
Testing the regula.dev on US it is working, but here in Brazil I have problems to render the page:
https://www.webpagetest.org/result/210816_BiDc70_018403861f289417c5c08b0bec68b616/1/screen_shot/

**Comment by jason-fugue** [comment]
Thanks, @amioranza! You're absolutely right. It's an issue with our CloudFront configuration. We're in the process of deploying a fix now. I'll reply back once it's done.

**Comment by jason-fugue** [comment]
The deploy just finished, but we've seen it take ~30 minutes for some CloudFront changes to propagate. If you've got time, would be able to check back on it to see if it's resolved?

**Comment by amioranza** [comment]
Sure, np, I'll do it and report back.

**Comment by amioranza** [comment]
It was fast on my region, it's working:
![image](https://user-images.githubusercontent.com/30518346/129618920-a023d48d-ea8f-4d3f-acf2-095d81f7f07d.png)

**Comment by amioranza** [comment]
Thanks!

**Comment by jason-fugue** [comment]
Awesome! Thanks again for your help troubleshooting this!
