### ISSUE TITLE
[ENHANCEMENT] Rule FG_R00100 - Support different ways to implement the bucket policy

### ISSUE THREAD

**Issue by rsareth** [fugue/regula#182]
Hi,

We are still testing your tools in version `v1.2.0, build 8537662, built with OPA v0.28.0`. But there is an annoying issue for us.

If we don't implement as documented (https://docs.fugue.co/FG_R00100.html), regula notifies us that we didn't set the bucket policy properly. In our case, we have some bucket policies coded in a **data resource aws_iam_policy_document**. And when we read how the rule was coded, if we were right, it is clear that the rule checks specifically what it is documented.

This is how it is written and not read properly by regula:
```
data "aws_iam_policy_document" "b" {
  version = "2012-10-17"
  statement {
    sid     = "DenyUnsecureAccess"
    actions = ["s3:*"]
    effect  = "Deny"

    principals {
      identifiers = ["*"]
      type        = "*"
    }

    resources = [
      aws_s3_bucket.b.arn,
      "${aws_s3_bucket.b.arn}/*",
    ]

    condition {
      test     = "Bool"
      values   = ["false"]
      variable = "aws:SecureTransport"
    }
  }
}

resource "aws_s3_bucket_policy" "b" {
  bucket = aws_s3_bucket.emr_logs.id
  policy = data.aws_iam_policy_document.b.json
}
```

We think you need to improve your HCL interpreter or your rule.

What do you think ?

**Comment by rsareth** [comment]
I've made a 3rd test. If you put the tf code in the same file, regula raises the same problem.

### Scenario 3
```hcl
# ##### b
# data "aws_iam_policy_document" "b" {
#   version = "2012-10-17"
#   statement {
#     sid     = "DenyUnsecureAccess"
#     actions = ["s3:*"]
#     effect  = "Deny"

#     principals {
#       identifiers = ["*"]
#       type        = "*"
#     }

#     resources = [
#       aws_s3_bucket.b.arn,
#       "${aws_s3_bucket.b.arn}/*",
#     ]

#     condition {
#       test     = "Bool"
#       values   = ["false"]
#       variable = "aws:SecureTransport"
#     }
#   }
# }

resource "aws_s3_bucket_policy" "b" {
  bucket = aws_s3_bucket.b.id

  policy = jsonencode({
    Version = "2012-10-17"
    Id      = aws_s3_bucket.b.id

    Statement = [
      {
        Sid       = "DenyUnsecureAccess"
        Effect    = "Deny"
        Principal = "*"
        Action    = "s3:*"
        Resource = [
          aws_s3_bucket.b.arn,
          "${aws_s3_bucket.b.arn}/*",
        ]
        Condition = {
          Bool = {
            "aws:SecureTransport" = "false"
          }
        }
      }
    ]
  })
}

resource "aws_s3_bucket" "b" {
  bucket = "b"
}

###### c
data "aws_iam_policy_document" "c" {
  version = "2012-10-17"
  statement {
    sid     = "DenyUnsecureAccess"
    actions = ["s3:*"]
    effect  = "Deny"

    principals {
      identifiers = ["*"]
      type        = "*"
    }

    resources = [
      aws_s3_bucket.c.arn,
      "${aws_s3_bucket.c.arn}/*",
    ]

    condition {
      test     = "Bool"
      values   = ["false"]
      variable = "aws:SecureTransport"
    }
  }
}

resource "aws_s3_bucket_policy" "c" {
  bucket = aws_s3_bucket.c.id
  policy = data.aws_iam_policy_document.c.json
}

resource "aws_s3_bucket" "c" {
  bucket = "c"
}

```

```
$ regula run regula/s3_b.tf # or regula run regula

[...]

FG_R00100: S3 bucket policies should only allow requests that use HTTPS [Medium]

  [1]: aws_s3_bucket.b
       in regula/s3_b.tf:54:1

[...]

Found 11 problems.

```

And with the uncommented data, it detects the same problem.

**Comment by jaspervdj-luminal** [comment]
Hey @rsareth!  I was looking into this a bit today.  I've been able to reproduce the results and it seems like there's several issues.  Thanks a lot for reporting this in so much detail!  I'll let you know as soon as we make progress on fixing these problems.

**Comment by jaspervdj-luminal** [comment]
Hey @rsareth,

One of the issues at play here was a bug in our S3 policies library that triggered different behavior depending on whether or not `aws_iam_policy_document` data documents were present.  This is why you were seeing inconsistent numbers when (un)commenting out code or running with different files.  A fix for this was added in 2f1381e6ceadebfa31c7898f36057eb1f25d2e3e and we've released a new version [v1.3.1](https://github.com/fugue/regula/releases/tag/v1.3.1) which includes this fix.

There is still an outstanding issue with `jsonencode`, which we're working on now, but `aws_iam_policy_document` resources should work fine.

**Comment by rsareth** [comment]
Hey @jaspervdj-luminal 

Thank you for keeping me informed. So, I'm waiting for the fix on `jsonencode`.

Regards,
Rasmey

**Comment by jason-fugue** [comment]
Hi, @rsareth! Whenever you get a chance, could you please try [the latest release (v1.3.2)](https://github.com/fugue/regula/releases/tag/v1.3.2) and see if this issue is resolved for you?

Thanks in advance,
Jason

**Comment by rsareth** [comment]
Hey @jason-fugue and @jaspervdj-luminal,

Thank you for the fix. With the tests we provided in this ticket, we can confirm that everything is fine now.

BTW, nice to have the link to the rule page describing the issue.

Regards,
Rasmey
