### ISSUE TITLE
Can we write Warning rules ?

### ISSUE THREAD

**Issue by ninjahck** [fugue/regula#183]
Like I wanted to write warning rules instead of deny as some of our sources are non-compliance but we wanted them to be created like for example

s3 bucket logging disabled 

can we do that in rego?

**Comment by jason-fugue** [comment]
Hi, @ninjahck! Yes, you can write warning rules. We have an [S3 access logging rule](https://github.com/fugue/regula/blob/master/rego/rules/tf/aws/s3/bucket_access_logging.rego) that we can copy for this example. What I've done below is change the `severity` field in the `__rego__metadoc__` section to `Informational`:

```Open-Policy-Agent
# rules/example_rule.rego
package rules.s3_bucket_logging_warning

__rego__metadoc__ := {
  "custom": {
    "severity": "Informational"
  },
  "description": "S3 bucket access logging should be enabled. Enabling server access logging provides detailed records for the requests that are made to a S3 bucket. This information is useful for security and compliance auditing purposes.",
  "title": "S3 bucket access logging should be enabled"
}

resource_type = "aws_s3_bucket"

default allow = false

allow {
  _ = input.logging[_]
}
```

By default, `regula` will exit with a non-zero (failure) status when a rule fails with any severity. We can change that behavior with the `--severity` flag:

```shell
# This will tell regula to only exit non-zero when the rule severity is "Low" or higher
regula run --include rules/example_rule.rego --severity low ...
```


Keep in mind that with this particular example, we already have a rule for S3 access logging. If you'd like to disable all of the built-in rules you can use the `--user-only` flag. Or if you only want to disable that single rule (`FG_R00274`), you can write a configuration file like:

```Open-Policy-Agent
# config/example_config.rego
package fugue.regula.config

rules[rule] {
  rule := {
    "rule_id": "FG_R00274",
    "status": "DISABLED"
  }
}
```

Then to include your configuration file, you'd run `regula` like:

```shell
regula run --include rules/example_rule.rego --include config/example_config.rego --severity low ...
```

**Comment by ninjahck** [comment]
Got it thanks 👍
