### ISSUE TITLE
We love regula!

### ISSUE THREAD

**Issue by dwilliams782** [fugue/regula#204]
Hi team,

Not an issue or bug, but we at [loveholidays](https://www.loveholidays.com/) recently posted about how we have incorporated Regula into our Terraform + Atlantis + Conftest pipeline:

https://tech.loveholidays.com/enforcing-best-practice-on-self-serve-infrastructure-with-terraform-atlantis-and-policy-as-code-911f4f8c3e00

Wanted to share with the Fugue team as the Regula Rego framework helped us tremendously with designing our Policy as Code solution, and I haven't seen anywhere else talking about integrating Regula with Conftest in an Atlantis pipeline yet.

Wasn't sure how to reach you guys, hence the GH issue. Thanks for a great product!

**Comment by dmitri-lerko** [comment]
Absolutely awesome software, thank you for all the great effort!

**Comment by curtis-fugue** [comment]
@dwilliams782 - we really appreciate this note and the awesome shout out in your blog! It definitely means a lot to the team. 

Your post is great by the way. I don't think I've come across such a thorough, hands-on walk through of using Atlantis and a policy as code framework. Nice job.

Thanks for working with us and please give the latest Regula CLI a try sometime and let us know what you think. You can also reach the team at `regula@fugue.co`.
