### ISSUE TITLE
FG_R00377 and FG_R00041 conflict with each other

### ISSUE THREAD

**Issue by alleynec** [fugue/regula#222]
The aws TF rule FG_R00377 allows for internet traffic (0.0.0.0/0) from ports 80 and 443. However, FG_R00041 disallows internet traffic from port 80. In my opinion, internet traffic from port 80 should be allowed for simple static sites. Here is the security group code that fails on FG_R00041. (var.port is defined as 80)
- - - - - - - - - - - - - - - - - - - - - - - - 
resource "aws_security_group" "lb" {
  name        = "tf-ecs-alb"
  description = "controls access to the ALB"
  vpc_id      = aws_vpc.pavpc.id

  ingress {
    protocol    = "tcp"
    from_port   = var.port
    to_port     = var.port
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = local.tag_name
    Tier = local.tag_tier_public
  }
}

**Comment by jason-fugue** [comment]
This got closed automatically when I merged.

**Comment by alleynec** [comment]
I ended up using port 443 for http.
