### ISSUE TITLE
Add support for terraform modules

### ISSUE THREAD

**Issue by valdisrigdon** [fugue/regula#23]
We make extensive use of terraform modules, but it appears that only the top-level resources in a project are included in `configuration_resources` and `planned_values_resources`.

I experimented with trying to change `lib/fugue_regula.rego` but I wasn't able to get very far.

The Terraform JSON output has `planned_values` map with `resources` inside the `root_module` key. But `root_module` also has a `child_modules` key, with a list of maps, and those have `resource` keys as well.

**Comment by valdisrigdon** [comment]
If changing `lib/fugue_regular.rego` is the right path forward, I can try to open a PR.

**Comment by jaspervdj-luminal** [comment]
Thanks for opening a ticket @valdisrigdon!  Changing `lib/fugue_regula.rego` is definitely how I would fix this -- the goal of that file is to do all the heavy lifting such that the rules themselves can be simple.

A PR would be more than welcome; but please don't hesitate to ping me for help if you can use it.

**Comment by jaspervdj-luminal** [comment]
@valdisrigdon Just to keep you up to date with progress -- I have an approach in #25 that works for the example I am testing this with:

- [Terraform Config](https://github.com/jaspervdj-luminal/example-terraform-modules/tree/89a426dc646af4484abe9149da40a97fd165a32a)
- [Plan JSON](https://github.com/fugue/regula/blob/79bee61a89cafbf5645af2b7bb4641dbf3c402c4/tests/lib/resource_view_modules_test.rego#L16)
- [Resulting resources view](https://github.com/fugue/regula/blob/79bee61a89cafbf5645af2b7bb4641dbf3c402c4/tests/lib/resource_view_modules_test.rego#L586) with an example of a resource reference [here](https://github.com/fugue/regula/blob/79bee61a89cafbf5645af2b7bb4641dbf3c402c4/tests/lib/resource_view_modules_test.rego#L629)

The PR needs some more documentation & polish, but it's looking good for now!

**Comment by valdisrigdon** [comment]
@jaspervdj-luminal This is awesome!

**Comment by jaspervdj-luminal** [comment]
I did some more testing and things look alright -- we've merged the branch and tagged this `v0.1.0`.  Please let me know if there's any other issues!
