### ISSUE TITLE
Make remediation doc url a part of rule metadata

### ISSUE THREAD

**Issue by darrendao** [fugue/regula#236]
Currently, it looks like the remediation doc URLs are stored in https://github.com/fugue/regula/blob/master/rego/remediation.yaml, and because of that, we cannot have remediation doc URL for CUSTOM rules. Would it make more sense to make remediation doc URL a part of a rule metadata? For example, something like this
```
__rego__metadoc__ := {
  "custom": {
    "controls": {
      "CIS-AWS_v1.3.0": [
        "CIS-AWS_v1.3.0_2.2.1"
      ]
    },
    "severity": "High"
  },
  "description": "My custom rule",
  "id": "CUSTOM_123",
  "title": "customer rule",
  "rule_remediation_doc": "https://example.com"
}
```
To be backward compatible, we can still have the remediation doc URLs defined in remediation.yaml. Just treat the value in the rule metadata with higher precedence and fall back to remediation.yaml if it's not there in the metadata. Thoughts on this? I can submit a PR if this sounds like a good idea.

**Comment by jason-fugue** [comment]
Hi, @darrendao! Yes that makes a lot of sense and we would definitely appreciate the PR. If you do take that on, could you please nest `rule_remedation_doc` under `custom`? Like:

```open-policy-agent
__rego__metadoc__ := {
  "custom": {
    "controls": {
      "CIS-AWS_v1.3.0": [
        "CIS-AWS_v1.3.0_2.2.1"
      ]
    },
    "severity": "High",
    "rule_remediation_doc": "https://example.com"
  },
  "description": "My custom rule",
  "id": "CUSTOM_123",
  "title": "customer rule"
}

```

**Comment by darrendao** [comment]
@jason-fugue PR created https://github.com/fugue/regula/pull/247
