### ISSUE TITLE
using regula on gitlab

### ISSUE THREAD

**Issue by ghost** [fugue/regula#48]
Hi,

I want to use regula framework on gitlab. For that do I need to right a custom docker file where the CI will run or is there any other option. Can someone please guide?
Thanks in advance.

**Comment by jaspervdj-luminal** [comment]
Hi @venkat24p!  It should definitely be possible to run Regula on GitLab without any changes to Regula itself.  There is an example of a GitHub action [here](https://github.com/fugue/regula-action) that also has a Dockerfile that installs all necessary components -- maybe that's a good place to start from?  Let me know if you need more help!
