### ISSUE TITLE
Clarification around regula-action license

### ISSUE THREAD

**Issue by tom-dudley** [fugue/regula#74]
Hello, I was wondering if someone might be able to clarify the licensing around the 'regula-action' repository and whether or not it's Apache 2.0. The repository didn't look particularly active so I hope you don't mind me asking this here.

Thanks in advance.

**Comment by jaspervdj-luminal** [comment]
Hi @tom-dudley, thanks for opening the issue. Yes, we relicensed everything to Apache 2.0 since it's more permissive.  However, it seems I forgot to update the other repositories, my bad!  I'll go fix that now.
