### ISSUE TITLE
Clarification how it works

### ISSUE THREAD

**Issue by marc181982** [fugue/regula#75]
Went through the documentation a couple of times, but i'm still completely confused.

This article https://github.com/fugue/example-tf-circleci-part-2 points to a file named regula-check.sh that according to the documentation runs regula (??), but i only see a script with a function that generates the plan and outputs it to a JSON file. What exactly is the regula part? Is it the script?

If i open this link https://github.com/fugue/regula/blob/master/bin/regula i see a completely different script? 

Also this part: _Walks through the imported Terraform modules and merges them into a flat format._ I've tried searching for this step, but couldn't find any? Except a simple convert to a JSON plan.

**Comment by jaspervdj-luminal** [comment]
@marc181982 Thanks for opening this issue!

One of the implicit goals of Regula is to do as much as possible within Rego itself.  That way, it can be easily used with other Rego-based projects, for example the way it's used with Conftest in that article.

This includes walking through the imported terraform modules -- that's done [in this file](https://github.com/fugue/regula/blob/master/lib/fugue_resource_view.rego), which is used within Rego before actually evaluating the rules.

As a result of that, the wrapper that actually start Regula (`bin/regula`) is very simple and short.  This means it's easy to replace in CI if you want to run it slightly differently, or you could replace it by Go code that calls `opa` directly.  That is what happens in this article, they swap out plain `opa` for `conftest` in the wrapping script.

I hope this makes things a bit more clear!

**Comment by marc181982** [comment]
A little bit more clear, but i'm still a bit confused. Seems like you developed a great solution so i'm trying to understand the details, unfortunately i'm unable to find those in the documentation. 

Like for example the step below in the pipeline, this installs Regula but there's also the regula-check.sh. If i open the file i can see that both contain a function to convert the Terraform plan to JSON. So why do i need them both?

          name: regula-install
          command: |
            wget -O regula.tar.gz https://github.com/fugue/regula/archive/v0.5.0.tar.gz
            sudo mkdir -p /opt/regula
            sudo tar -xf regula.tar.gz --strip-components=1 -C /opt/regula
            rm regula.tar.gz

**Comment by jaspervdj-luminal** [comment]
So, I would say these are the components at play here:

 -  `rules/` contains the rules
 -  `lib/` contains all of the logic to take in terraform plan JSON and to produce reports
 -  `bin/regula` is a very simple script that invokes OPA with the right parameters to use `lib/` and `rules/`

However, `bin/regula` is very simple and easily replaceable (by `regula-check.sh`, for example).  So what we're doing in the example in the pipeline is installing Regula so we have `rules/` and `lib/`, but we don't really care about `bin/regula`.  But since it's so small it's really not worth removing it from the installation.  Does that clear things up?

**Comment by marc181982** [comment]
Ah i see, but with `bin regula` ts

**Comment by jaspervdj-luminal** [comment]
> Ah i see, but with `/bin/regula` you're refering to the file that is moved to `opt/regula`? This explains how it works, i got confused because i noticed two scripts even though the `opt/regula` wasn't called during the execution of the pipeline.

Yep, exactly, the file is moved there but not used; only `/opt/regula/lib` is used.

> With the logic in the Rego framework, does it also mean that it is possible to write custom rules and use them in the Fugue product? Meaning, that it is possible to use the same custom policies for pre-deployment and post-deployment checks?

Yes, this is true as well: the format of the rules is designed in a way that they work as pre-deployment (Regula) as well as post-deployment (Fugue Custom Rules) checks without modifications to the Rego code.

**Comment by marc181982** [comment]
Thanks! This helps, closing issue
